spring:
  config:
    import:
      - config.yaml
  exposed:
    generate-ddl: false
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
sentry:
  dsn: ${SENTRY_DSN}
