discord:
  bot-token: ${DISCORD_BOT_TOKEN}
  channel: ${DISCORD_CHANNEL_ID}
  admin: ${DISCORD_ADMIN_ID}
bank:
  cost: ${BANK_COST}
selenium:
  use-remote: ${SELENIUM_USE_REMOTE}
  host: ${SELENIUM_REMOTE_HOST}
  use-headless: ${SELENIUM_USE_HEADLESS}
pop3:
  host: ${POP3_HOST}
  port: ${POP3_PORT}
  user: ${POP3_USERNAME}
  password: ${POP3_PASSWORD}
supabase:
  url: ${SUPABASE_URL}
  key: ${SUPABASE_SECRET_KEY}
cors:
  origin: ${CORS_PRODUCTION_ORIGIN}
public-api:
  password: ${PUBLIC_API_PASSWORD_BCRYPT}
  secret: ${PUBLIC_API_TOKEN_SECRET}