package me.daegyeo.netflixchecker.enum

enum class MetricsKey(val key: String) {
    CODE_GENERATED_COUNT("CODE_GENERATED_COUNT"),
    CODE_GENERATED_COUNT_BY_MONTH("CODE_GENERATED_COUNT_{YEAR}_{MONTH}"),
    LATEST_CRAWLING_STATUS("LATEST_CRAWLING_STATUS"),
    LATEST_CRAWLING_TIME("LATEST_CRAWLING_TIME")
}